config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

Foodoo::Application.routes.draw do
  constraints format: /html|js|json|pdf/ do

    scope module: 'public' do
      get '/agb' => 'pages#agb', as: 'agb'
      get '/kontakt' => 'pages#contact', as: 'contact'
      get '/ueber-uns' => 'pages#about_us', as: 'about_us'
      get '/impressum' => 'pages#imprint', as: 'imprint'
      get '/so-funktionierts' => 'pages#how_it_works', as: 'how_it_works'
      get '/faq' => 'pages#faq', as: 'faq'

      # resources :events
      resources :event_appointments, only: [:show],  path: 'events'
      resources :users, only: [:show]
      resources :blog_entries, only: [:index, :show], path: 'blog' do
        get "/:year/:month/:day/:alias" => "blog_entries#show", as: 'complete', on: :collection
      end
      get '/blog-archiv', to: redirect('/blog')

      resources :errors, only: [:error_404, :error_500]
      resource :newsletter_subscriptions, only: [:create, :edit, :update] do
        get :success
      end

      if Rails.env.development?
        get '/templates' => 'pages#templates'
      end
    end


    # --------------------------------------------
    # intern (internal user area)
    devise_for :users,
      path: '',
      controllers: {
        sessions: 'auth/sessions',
        passwords: 'auth/passwords',
        unlocks: 'auth/unlocks',
        confirmations: 'auth/confirmations',
        registrations: 'auth/registrations',
        omniauth_callbacks: 'auth/omniauth_callbacks'
      },
      path_names: {
        sign_in: 'anmelden',
        sign_out: 'abmelden',
        password: 'neues-passwort',
        confirmation: 'konto-bestaetigen',
        registration: 'registrierung',
        unlock: 'entsperren'
      },
      skip: [:passwords, :confirmations, :unlocks]
    as :user do
      get 'abmelden' => 'devise/sessions#destroy'
      get 'registrierung' => 'auth/registrations#new'

      # passwords
      post 'neues-passwort' => 'auth/passwords#create', as: 'user_password'
      get 'neues-passwort' => 'auth/passwords#new', as: 'new_user_password'
      get 'neues-passwort/neu' => 'auth/passwords#edit', as: 'edit_user_password'
      patch 'neues-passwort/neu' => 'auth/passwords#update'
      put 'neues-passwort/neu' => 'auth/passwords#update'

      # confirmations
      get 'konto-bestaetigen' => 'auth/confirmations#new', as: 'new_user_confirmation'
      get 'konto-bestaetigen/bestaetigen' => 'auth/confirmations#show', as: 'user_confirmation'
      post 'konto-bestaetigen/bestaetigen' => 'auth/confirmations#create'

      # unlocks
      get 'entsperren' => 'auth/unlocks#new', as: 'new_user_unlock'
      get 'entsperren/entsperren' => 'auth/unlocks#show', as: 'user_unlock'
      post 'entsperren/entsperren' => 'auth/unlocks#create'
    end

    namespace :internal, path: 'profil' do
      resources :events, only: [:new, :create] do
        get :back, on: :member
        get :gallery, on: :member
        get :successfully_created, on: :member, path: 'erfolgreich-erstellt'
        resource :event_data, only: [:show], path: 'kontakt-daten'
      end
      resources :event_appointments, only: [:edit, :update] do
        delete 'destroy'
        delete 'uninvite/:participation_id' => :uninvite, as: 'uninvite'
        delete 'not_appear/:participation_id' => :not_appear, as: 'not_appear'
        resource :participation, only: [:show, :new, :create, :destroy], path: 'teilnahme', path_names: { new: 'buchen' }
        resource :rating, only: [:new, :create, :show], path: 'bewertung', path_names: { new: 'bewerten' }
      end
      resources :images
      resource :user, only: [:show, :edit, :update] do
        get :gallery, on: :member
        get :edit_password, to: 'users#edit_password'
        patch :update_password, to: 'users#update_password'
        resources :user_languages, only: [:index, :new, :create, :destroy] do
          put :update_all, on: :collection
        end
      end
      resources :images, only: [:create, :index, :new, :show, :destroy]
    end


    # --------------------------------------------
    # devise & backend
    devise_for :backend_users

    namespace :backend do
      get '/' => 'dashboards#show'

      resource :dashboard, only: :show
      resources :events, only: [:show, :index, :edit, :update] do
        put :decline, on: :member
        put :approve, on: :member
        put :submit, on: :member
        resources :images, only: [:new, :create, :destroy]
      end
      resources :user_exports
      resources :blog_entries, except: [:show], path: 'blog', shallow: true do
        post :toggle_published, on: :member
        resources :blog_elements, except: [:index, :show] do
          put :position_up, on: :member
          put :position_down, on: :member
        end
      end
      resources :cities, except: [:show], path: 'staedte'
      resources :users, only: [:index, :show], shallow: true
      resources :backend_users, except: [:show]
      resources :background_jobs, only: [:index]
    end


    # --------------------------------------------
    # defaults

    get 'errors/error_404'
    get 'errors/oauth_failure'

    root 'public/event_appointments#index'


    # --------------------------------------------
    # sidekiq

    constraints(Constraint::Sidekiq) do
      mount Sidekiq::Web, at: "/backend/sidekiq", as: :sidekiq
    end


    # --------------------------------------------
    # mail testing

    if Rails.env.development?
      mount UserMailerPreview => 'user_mail_view'
      mount EventMailerPreview => 'event_mail_view'
    end


    # --------------------------------------------
    # catch all

    unless Rails.application.config.consider_all_requests_local
      match '*not_found', to: 'errors#error_404', via: [:get]
    end

  end
end

app/models/event.rb
# database attributes
# owner, title, description, courses_count, max_f_guest_count
# max_guest_count, max_m_guest_count, min_m_guest_count, min_guest_count
# min_f_guest_count, price, category, duration, repetition
# address_city, address_zip, address_street, address_addition
# latitude, longitude, fake_latitude, fake_longitude
# ring_at, floor, state, sex_direction, self_participation

# attributes
# category, owner, transaction, images

class Event < ActiveRecord::Base
  # SEX_DIRECTIONS = ['hetero', 'homo']
  SEX_DIRECTIONS = ['mf', 'mm', 'ff']

  # paranoid
  acts_as_paranoid

  # relations
  belongs_to :category, class_name: 'Category'
  belongs_to :owner, class_name: 'User', inverse_of: :events

  has_many :images, as: :imaged
  has_many :event_drinks, class_name: "Relation::EventDrink"
  has_many :event_appointments
  has_many :event_event_informations, class_name: "Relation::EventEventInformation"
  has_many :event_informations, through: :event_event_informations

  # ---------------------------------------------------
  # validations
  validates_presence_of :owner

  #before_validation :check_max_guest_even_or_odd

  def max_guest_count_sum
    return if dating? && self_participation

    if sex_direction == 'mf'
      if max_f_guest_count.to_i > 0 || max_m_guest_count.to_i > 0
        sum = max_f_guest_count.to_i + max_m_guest_count.to_i
        if sum != max_guest_count
          errors.add(:max_guest_count, 'is not the result of max_m_guest_count + max_f_guest_count.')

          return false
        end
      end
    elsif sex_direction == 'mm'
      if max_m_guest_count.to_i != max_guest_count
        errors.add(:max_guest_count, 'is not the equal max_m_guest_count.')

        return false
      end
    elsif sex_direction == 'ff'
      if max_f_guest_count.to_i != max_guest_count
        errors.add(:max_guest_count, 'is not the equal max_f_guest_count.')

        return false
      end
    end

    return true
  end

  def dating_arrangement
    return unless dating?

    m = max_m_guest_count.to_i
    f = max_f_guest_count.to_i

    if sex_direction == 'mf'
      if self_participation
        if owner.male? && (m+1 != f)
          errors.add(:max_m_guest_count, 'is not the equal max_f_guest_count-1.')
        elsif owner.female? && (m != f+1)
          errors.add(:max_m_guest_count, 'is not the equal max_f_guest_count+1.')
        end
      elsif !self_participation && m != f
        errors.add(:max_m_guest_count, 'is not the equal max_f_guest_count.')
      end
    elsif sex_direction == 'mm'
      if self_participation && owner.female?
        errors.add(:sex_direction, 'you are not male.')
      elsif self_participation && (m+1)%2 != 0
        errors.add(:max_m_guest_count, 'is not even with you.')
      elsif self_participation && m+1 != max_guest_count
        errors.add(:max_m_guest_count, 'is not equal max_guest_count - 1.')
      elsif !self_participation && m%2 != 0
        errors.add(:max_m_guest_count, 'is not even.')
      elsif !self_participation && m != max_guest_count
        errors.add(:max_m_guest_count, 'is not equal max_guest_count.')
      end
    else
      if self_participation && owner.male?
        errors.add(:sex_direction, 'you are not female.')
      elsif self_participation && (f+1)%2 != 0
        errors.add(:max_f_guest_count, 'is not even with you.')
      elsif self_participation && f+1 != max_guest_count
        errors.add(:max_f_guest_count, 'is not equal max_guest_count - 1.')
      elsif !self_participation && f%2 != 0
        errors.add(:max_f_guest_count, 'is not even.')
      elsif !self_participation && f != max_guest_count
        errors.add(:max_f_guest_count, 'is not equal max_guest_count.')
      end
    end
  end

  # ---------------------------------------------------
  # geocoding
  before_validation :fill_max_counts

  # ---------------------------------------------------
  # nested stuff
  accepts_nested_attributes_for :category
  accepts_nested_attributes_for :event_event_informations
  accepts_nested_attributes_for :owner
  accepts_nested_attributes_for :event_appointments, allow_destroy: true

  bitmask :repetition, :as => [:daily, :weekly, :monthly, :not]
  # ---------------------------------------------------
  # state machine

  state_machine :state, initial: :started do
    state :started

    state :create_1 do
      # presence
      validates_presence_of :title
      validates_presence_of :category_id
      validates_presence_of :sex_direction, :if => :is_dating_dinner?
      validates_inclusion_of :self_participation, in: [true, false], :if => :is_dating_dinner?
      validates_presence_of :max_guest_count
      validates_presence_of :courses_count
      validates_presence_of :duration
      validates_presence_of :description
      validates_presence_of :images
      validates_presence_of :category
      validate :city_restriction

      # format
      validates :sex_direction, inclusion: { in: SEX_DIRECTIONS }, :if => :is_dating_dinner?
      validates :max_guest_count, numericality: { only_integer: true, greater_than: 0 }
      validates :max_guest_count, numericality: { only_integer: true, greater_than: 0 }
      validate :dating_arrangement
    end

    state :create_2 do
      # presence step 1
      validates_presence_of :title
      validates_presence_of :category_id
      validates_presence_of :sex_direction, :if => :is_dating_dinner?
      validates_inclusion_of :self_participation, in: [true, false], :if => :is_dating_dinner?
      validates_presence_of :max_guest_count
      validates_presence_of :courses_count
      validates_presence_of :duration
      validates_presence_of :description
      validates_presence_of :images
      validates_presence_of :category

      # presence step 2
      validates_presence_of :person_name
      validates_presence_of :address_city
      validates_presence_of :address_street
      validates_presence_of :address_district
      validates_presence_of :address_zip
      # validates_presence_of :ring_at
      # validates_presence_of :floor
      validates_presence_of :latitude
      validates_presence_of :longitude
      validates_presence_of :fake_latitude
      validates_presence_of :fake_longitude
      validate :city_restriction

      # format step 1
      validates :sex_direction, inclusion: { in: SEX_DIRECTIONS }, :if => :is_dating_dinner?
      validates :max_guest_count, numericality: { only_integer: true, greater_than: 0 }
      validate :dating_arrangement
    end

    state :created do
      # presence step 1
      validates_presence_of :title
      validates_presence_of :category_id
      validates_presence_of :sex_direction, :if => :is_dating_dinner?
      validates_inclusion_of :self_participation, in: [true, false], :if => :is_dating_dinner?
      validates_presence_of :max_guest_count
      validates_presence_of :courses_count
      validates_presence_of :duration
      validates_presence_of :description
      validates_presence_of :images
      validates_presence_of :category

      # presence step 2
      validates_presence_of :person_name
      validates_presence_of :address_city
      validates_presence_of :address_street
      validates_presence_of :address_zip
      # validates_presence_of :ring_at
      # validates_presence_of :floor
      validates_presence_of :latitude
      validates_presence_of :longitude
      validates_presence_of :fake_latitude
      validates_presence_of :fake_longitude

      # presence step 3
      validates_presence_of :price

      # format step 1
      validates :sex_direction, inclusion: { in: SEX_DIRECTIONS }, :if => :is_dating_dinner?
      validates :max_guest_count, numericality: { only_integer: true, greater_than: 0 }
      validate :dating_arrangement

      #format step 3
      validates_acceptance_of :agb_confirmation, accept: true
      #validates_acceptance_of :debit_authorization, accept: true
    end

    state :approved do
      validates_presence_of :description
    end

    state :created do
      validates_presence_of :description
    end

    state :declined do
      validates_presence_of :description
    end

    state :waiting_for_approval do
      validates_presence_of :description
    end

    #transitions
    event :back do
      transition create_2: :create_1
      transition create_1: :started
    end

    event :next do
      transition started: :create_1
      transition create_1: :create_2
      transition create_2: :created
    end

    event :create do
      transition all: :created
    end

    event :submit do
      transition created: :waiting_for_approval
      transition declined: :waiting_for_approval
    end

    event :approve do
      transition waiting_for_approval: :approved
    end

    event :decline do
      transition waiting_for_approval: :declined
      transition approved: :declined
    end

    after_transition to: :waiting_for_approval, do: :notify_for_new_event
  end

  # callbacks
  after_initialize :set_default_state

  # methods

  def set_default_state
    self.state ||= 'started'
  end

  def drinks
    self.event_drinks.map{|ed| ed.drink }.compact
  end

  def drink_ids
    self.event_drinks.map{|ed| ed.drink_id }.compact
  end

  def drink_ids=(values)
    relations = []

    if values.present?
      values = values.uniq

      values.each do |drink_id|
        unless self.drink_ids.include?(drink_id)
          relations << Relation::EventDrink.new(event: self, drink_id: drink_id)
        end
      end
    end

    self.event_drinks = relations
  end

  def drinks=(values)
    self.drink_ids = values.map(&:id)
  end

  def open_ends=(values)
    self.open_end = values.first
  end

  def open_ends
    [self.open_end]
  end

  def own_max_guest_count=(value)
    self.max_guest_count = value if value.present?
  end

  def event_appointment
    self.event_appointments.first
  end

  def event_appointment=(values)
    appointment = self.event_appointments.first

    if appointment.nil?

app/controllers/internal/base_controller.rb
class Internal::BaseController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_profile_completion

  layout 'public'

  protected

  def check_profile_completion
    unless current_user.profile_completed?
      flash.keep
      flash.alert = I18n::t('public.flash.profile_incomplete')

      redirect_to edit_internal_user_path
    end
  end

end

app/controllers/internal/event_data_controller.rb
class Internal::EventDataController < Internal::BaseController

  def show
    participated_events = current_user.decorate.participated_events
    event_appointment = participated_events.detect{|ea| ea.event.id.to_s == params[:event_id]}
    @event = event_appointment.event if event_appointment

    if @event.nil?
      redirect_to(errors_error_404_path(not_found: request.original_url))
    end

    render layout: false

  end
  
end

app/controllers/internal/user_images_controller.rb
class Internal::UserImagesController < Internal::BaseController
  before_filter :images
  before_filter :main_image

  def index; end

  def create
    @image = Image.new(image_params)
    @image.imaged = current_user

    if @image.save
      redirect_to action: :index
    else
      render :index
    end
  end

  private

  def image_params
    params.require(:image).permit(
      :file
    )
  end

  def user
    @user ||= current_user
  end

  def images
    @images = user.images
  end

  def main_image
    @main_image ||= user.main_image
  end
end

app/views/internal/events/_event_gallery.html.haml
= render_cell :gallery, :show, @event, :event

app/views/internal/events/_new_step_1.html.haml
%section.container.event
  .headline-bar
    .inside
      .row
        .col-xs-12
          %h2
            %i.headline-icons.icon-meal
            Das Essen

  .inside
    .row
      .col-xs-12.form.eat{'data-owner-gender' => @event.owner.gender}
        .meal-image
        = form.input :title, placeholder: t('simple_form.labels.event.title_placeholder'), required: true

        = render_cell :form, :radios, form, :category_id, collection: @event.categories, required: true

        = render_cell :form, :radios, form, :sex_direction, collection: @event.sex_directions, required: true

        = render_cell :form, :radios, form, :self_participation, collection: @event.self_participations, required: true

        .row#guest-count
          .col-xs-12
            = render_cell :form, :radios, form, :max_guest_count, collection: @event.max_guest_counts, required: true
            = form.input :own_max_guest_count, label: false

        = render_cell :form, :radios, form, :courses_count, collection: @event.course_counts, required: true
        .row
          .col-xs-4
            = render_cell :form, :radios, form, :duration, collection: @event.durations, required: true
            .open-end
              = render_cell :form, :checkboxes, form, :open_ends, collection: @event.open_ends, required: true, show_label: false, input_html: {class: 'fbtn hover', label: ''}

        = render_cell :form, :checkboxes, form, :drink_ids, collection: @event.possible_drinks, input_html: {class: 'fbtn hover', label: t('simple_form.labels.event.drink_ids')}

        = form.input :description, required: true

%section.container.event
  .headline-bar
    .inside
      .row
        .col-xs-12
          %h2
            %i.headline-icons.icon-photo
            Fotos hinzufügen

  .inside
    .row
      .col-xs-12.photo.form
        = form.input :images, placeholder: t('simple_form.labels.event.title_placeholder'), label: false
        = render_cell :gallery, :show, @event, :event

  .inside
    .row
      .col-xs-12.next-button
        = render_cell :button, :medium_button, t('simple_form.labels.event.go_to_step_2'), {type: 'submit', class: 'active right'}

app/views/internal/events/_new_step_2.html.haml
%section.container.event
  .headline-bar
    .inside
      .row
        .col-xs-12
          %h2
            %i.headline-icons.icon-person
            Angaben zur Person

  .inside
    .row
      .col-xs-8.form
        .location-image
        .form-group
          = form.input :person_name, required: true, hint: t('simple_form.labels.event.owner_name_hint')
          = form.input :address_street, required: true, label: t('simple_form.labels.event.address_street')
    .row
      .col-xs-2.form
        = form.input :address_zip, required: true, input_html:{ class: 'small inline' }
      .col-xs-6.form
        = form.input :address_city, required: true, input_html:{ class: 'medium' }
    .row
      .col-xs-8.form
        = form.input :address_district, required: true, label: t('simple_form.labels.event.address_district')
    .row
      .col-xs-8.form
        .form-group
          = form.input :phone
    .row
      .col-xs-5.form
        .form-group
          %label
            = t('simple_form.labels.event.map')
          #event-create-google-map
          = form.input :latitude, as: :hidden, type: :float, input_html: { value: @event.latitude }
          = form.input :longitude, as: :hidden, type: :float, input_html: { value: @event.longitude }
      .col-xs-3.form
        .form-group.address_details
          = form.input :ring_at, input_html:{ class: 'small' }
          = form.input :floor, input_html:{ class: 'small' }
          = form.input :address_addition, as: :text, label: t('simple_form.labels.event.address_details'), input_html:{ class: 'small' }

    .row
      .col-xs-12.form
        .form-group.event_informations
          .buttons
            = render_cell :form, :checkboxes, form, :event_information_ids, collection: @event.informations, input_html: {class: 'fbtn-square-info hover'}, label: t('simple_form.labels.event.event_informations')

%section.container.event
  .inside
    .row
      .col-xs-12.next-button
        = render_cell :button, :medium, t('simple_form.labels.event.back_to_step_1'), back_internal_event_path(@event), {class: 'active left', type: 'submit'}
        = render_cell :button, :medium_button, t('simple_form.labels.event.go_to_step_3'), class: 'active right'

app/views/internal/events/_new_step_3.html.haml
%section.container.event
  .headline-bar
    .inside
      .row
        .col-xs-12
          %h2
            %i.headline-icons.icon-price
            Preis | Datum
  .inside
    .row.form
      .price-date-image
      .col-xs-12
        = form.simple_fields_for :event_appointments, @event.event_appointments.present? ? @event.event_appointments : EventAppointment.new do |sub_form|
          = render_cell(:form, :repetition_inputs, sub_form)

    .row
      .col-xs-12.repetitions

    .row
      .col-xs-3.col-xs-offset-1
        = render_cell(:form, :add_repetition, form)

    .row
      .col-xs-6.form
        = render_cell :form, :radios, form, :participation_until_hours, collection: @event.participation_until_hours_steps, required: true, label: t('simple_form.labels.event.participation_until_hours')
        %strong{ style: 'margin-top: -20px; display: block;' } vorher
    .row
      .col-xs-3.form
    .row
      .col-xs-3.form
        = form.input :float_price, as: :string, input_html:{ class: 'price', id: 'input', maxlength: '3', type: "number", min:"0", max:"999", step:"1"}, label: t('simple_form.labels.event.price'), value: "0", required: true

    .row
      .col-xs-5.form
        .form-group.text
          %p.bold
            = t('simple_form.labels.event.more_info')
            =link_to t('simple_form.labels.event.agb'), agb_path
        = render_cell :form, :boolean, form, :agb_confirmation, input_html: {'data-btn-type' => 'boolean hover'}

%section.container.event
  .inside
    .row
      .col-xs-12.next-button
        = render_cell :button, :medium, t('simple_form.labels.event.back_to_step_2'), back_internal_event_path(@event), {class: 'active left', type: 'submit'}
        = render_cell :button, :medium_button, t('simple_form.labels.event.create_event'), {class: 'active right', type: 'submit'}

app/views/internal/events/gallery.html.haml
= render 'event_gallery', event: @event

app/views/internal/events/new.html.haml
%section.container.event
  .inside
    .row
      .col-xs-4.steps
        .step-container{class: ("active" if @event.state?(:started))}
          #step1.step
          %p
            Das Essen
      .col-xs-4.steps
        .step-container{class: ("active" if @event.state?(:create_1))}
          #step2.step
          %p
            Die Location
      .col-xs-4.steps
        .step-container{class: ("active" if @event.state?(:create_2))}
          #step3.step
          %p
            Preis | Datum

= simple_form_for @event, url: internal_events_path, method: :post, html: { class: "standard-form" } do |f|
  - if @event.state?(:started)
    = render 'new_step_1', event: @event, form: f
  - elsif @event.state?(:create_1)
    = render 'new_step_2', event: @event, form: f
  - elsif @event.state?(:create_2)
    = render 'new_step_3', event: @event, form: f

- content_for :modal do
  #image-upload-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1", 'data-ajax-reload-url' => gallery_internal_event_path(@event), 'data-ajax-reload-container' => '#gallery', 'data-gallery-type' => 'vertical'}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
          %h4#myModalLabel.modal-title Bilderupload
        .modal-body
          = render_cell(:image, :upload, @event)

app/views/internal/events/successfully_created.html.haml
%section.container.event-created
  .inside
    .wrapper
      %h1.headline.centered
        = t('internal.event.created.headline')
      %h2.subheadline.centered
        = t('internal.event.created.subheadline')
      %p.text.centered
        = t('internal.event.created.info')
        = link_to t('internal.event.created.email'), '#'
      .buttons
        = render_cell :button, :normal, t('internal.event.created.startpage_link'), root_url, class: 'active'
        = render_cell :button, :normal, t('internal.event.created.event_link'), event_appointment_path(@event_appointment)
      .logo
        = image_tag('home-header-icon.png', alt: t('public.event_appointments.index.logo_img_alt'))